apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: demo-dev-env
spec:
  ports:
    - name: http
      port: 8081
  type: NodePort
  selector:
    apps: recruitment-service
